/* ============================================================
   TEMAS CURADOS — la "base dorada" del blog de Canedo Studio
   Cada tema: id único, tema (título guía), angulo (enfoque),
   img (escena fotográfica EN INGLÉS para la portada).
   El robot los usa primero; al agotarlos, pasa al modo híbrido
   (inspiración RSS + temas generados por IA).
   ============================================================ */

export const TOPICS = [

  /* ===== A. Chatbots y atención al cliente ===== */
  { id: "chatbot-24-7", tema: "El empleado que atiende a las 3 de la mañana (y no pide vacaciones)", angulo: "la demanda no respeta horarios; un chatbot sí", img: "a glowing smartphone on a dark bedside table at 3am showing an active chat conversation, city lights bokeh through the window, deep blue night tones with warm lamp accent, cinematic intimate mood" },
  { id: "chatbot-aprende", tema: "Un chatbot que aprende de tu negocio, no de internet", angulo: "entrenado con tus precios, tus servicios y tu tono", img: "a glowing holographic brain made of golden light particles connected by light threads to a small shop counter, dark elegant interior, cinematic depth of field, photographic realism" },
  { id: "chatbot-primer-minuto", tema: "El primer minuto: donde se gana o se pierde un cliente", angulo: "responder al instante multiplica las ventas; esperar las entierra", img: "a vintage chrome stopwatch glowing amber on a dark reflective desk, its hands frozen at the first minute, dramatic side lighting, macro detail, tense cinematic atmosphere" },
  { id: "chatbot-cualifica", tema: "No todos los que escriben son clientes: cómo un chatbot los distingue", angulo: "cualificar leads mientras duermes: curiosos fuera, compradores dentro", img: "an elegant brass sieve filtering streams of golden light particles on a dark marble table, some particles glowing brighter as they pass through, macro photography, dramatic lighting" },
  { id: "chatbot-sin-frustrar", tema: "Por qué la gente odia los chatbots viejos (y qué cambió con la IA)", angulo: "de menús rígidos a conversaciones que entienden", img: "an old dusty telephone with tangled cords on the left and a sleek glowing smartphone with flowing chat bubbles on the right, split dark studio scene, dramatic rim lighting" },
  { id: "chatbot-agenda", tema: "Del mensaje a la cita agendada: el chatbot que cierra por ti", angulo: "cuando detecta un cliente cualificado, ofrece horarios y agenda", img: "an open leather agenda on a dark executive desk with a golden pen writing an appointment by itself, warm banker lamp glow, venetian blind shadows, cinematic elegance" },
  { id: "chatbot-faq", tema: "Las 10 preguntas que tus clientes repiten (y que ya no deberías contestar tú)", angulo: "automatiza las respuestas frecuentes sin perder el trato humano", img: "multiple glowing speech bubbles floating in a dark room above a calm business owner reading a book, warm golden light, surreal but photographic, shallow depth of field" },
  { id: "chatbot-whatsapp-web", tema: "Chatbot en tu web o en tu WhatsApp: dónde conviene cada uno", angulo: "dos canales, dos comportamientos de cliente, una misma estrategia", img: "two glowing doorways of light side by side in a dark elegant hallway, one blue and one green, a silhouette of a customer choosing between them, cinematic perspective" },
  { id: "chatbot-tono", tema: "Que tu chatbot hable como tú (y no como un robot de película)", angulo: "el tono de marca también se puede automatizar", img: "a fountain pen transforming into a stream of glowing golden words that flow into a smartphone screen, dark writer desk, warm moody light, macro detail" },
  { id: "chatbot-ventas-nocturnas", tema: "Ventas nocturnas: el turno de noche que no cuesta un euro", angulo: "la mayoría de consultas llegan fuera de horario; ahí está el dinero", img: "a small shop at night with warm lights glowing inside and an illuminated open sign, empty quiet cobblestone street, dark sleeping city around it, cinematic wide shot" },
  { id: "chatbot-objeciones", tema: "Cómo un chatbot responde a la pregunta que más miedo te da: el precio", angulo: "manejar objeciones con datos y calma, siempre igual de bien", img: "a golden price tag glowing on a dark velvet cushion surrounded by soft light beams, elegant jewelry-store atmosphere, macro photography, luxurious detail" },
  { id: "chatbot-humano-relevo", tema: "El relevo perfecto: cuándo el chatbot debe pasar la conversación a un humano", angulo: "automatizar sin abandonar: la mano en el momento justo", img: "a relay race baton glowing gold being passed from a translucent holographic hand to a human hand, dark stadium background, dramatic spotlight, photographic realism" },

  /* ===== B. Reseñas y reputación online ===== */
  { id: "resena-momento-exacto", tema: "El momento exacto para pedir una reseña (casi nadie lo acierta)", angulo: "pedirla en el pico de satisfacción, no una semana después", img: "a golden star shape forming from light particles above a smartphone held in happy customer's hands, warm restaurant bokeh background, cinematic glow, photographic detail" },
  { id: "resena-mapa-tesoro", tema: "Tu ficha de Google Maps es un escaparate: así se convierte en imán", angulo: "fotos, reseñas y respuestas que empujan al cliente a llamarte a ti", img: "a glowing treasure map made of golden light lines on a dark wooden table with a smartphone showing a map pin, dramatic overhead light, adventure atmosphere, macro detail" },
  { id: "resena-responder", tema: "Responder reseñas: la parte del juego que tus competidores ignoran", angulo: "cada respuesta es un mini-anuncio público de tu profesionalidad", img: "an elegant fountain pen writing golden replies to floating glowing review cards in a dark sophisticated room, warm accent lighting, surreal photographic composition" },
  { id: "resena-negativa", tema: "La reseña negativa no es el enemigo: la mala gestión sí", angulo: "cómo un sistema desvía la queja a privado antes de que sea pública", img: "a dark stormy cloud over a smartphone transforming into a golden sunbeam as it passes through an elegant glass prism, dramatic studio lighting, symbolic photographic scene" },
  { id: "resena-flujo-constante", tema: "Por qué 5 reseñas al mes valen más que 50 de golpe", angulo: "Google premia la constancia, no los picos sospechosos", img: "a steady stream of small golden stars flowing like a river of light across a dark marble surface, long exposure photography style, elegant and hypnotic" },
  { id: "resena-whatsapp-peticion", tema: "El mensaje que consigue reseñas sin parecer insistente", angulo: "el texto exacto y el enlace directo, en el canal que el cliente ya usa", img: "a smartphone screen glowing with a warm friendly chat message and a shining five star icon, cozy dark cafe background bokeh, intimate photographic mood" },
  { id: "resena-competencia", tema: "Mira las reseñas de tu competencia: ahí está tu argumentario", angulo: "sus quejas son tus ventajas; su silencio, tu oportunidad", img: "a golden magnifying glass hovering over a dark city map made of glowing lights and small stars, detective atmosphere, dramatic side light, cinematic detail" },
  { id: "resena-estrellas-llamada", tema: "De las estrellas a la llamada: el recorrido mental del cliente local", angulo: "cómo decide a quién llama en una pantalla de tres resultados", img: "three glowing storefront silhouettes on a dark street with golden stars floating above them, one shining brighter, a customer silhouette walking toward it, cinematic night scene" },
  { id: "resena-video-fotos", tema: "Fotos y vídeos en tus reseñas: la prueba social que no se puede falsificar", angulo: "animar al cliente a subir su experiencia en imagen", img: "a smartphone camera capturing a glowing golden moment in an elegant dark restaurant, light particles floating, warm cinematic atmosphere, shallow depth of field" },
  { id: "resena-sistema-no-suerte", tema: "La reputación no es suerte: es un sistema que se enciende solo", angulo: "detectar, pedir, publicar, responder: las 4 piezas del embudo", img: "an intricate golden clockwork mechanism with small glowing stars as gears, dark elegant background, precision macro photography, dramatic lighting" },
  { id: "resena-perfil-completo", tema: "La ficha de Google que espanta clientes (y ni lo sabes)", angulo: "horarios mal, sin fotos, sin respuestas: los detalles que cuestan ventas", img: "an abandoned dusty shop window with a broken neon sign, a single beam of light revealing cobwebs, contrast with a glowing smartphone showing a perfect listing beside it, cinematic" },
  { id: "resena-cliente-feliz-invisible", tema: "Tu cliente más feliz también es el más silencioso", angulo: "sin un sistema, solo escribe el insatisfecho", img: "a happy customer silhouette glowing softly in gold walking away from a shop into the dark, unnoticed, while a single red spotlight glows far behind, cinematic storytelling" },

  /* ===== C. Diseño web que vende ===== */
  { id: "web-primer-vistazo", tema: "Tu web tiene 3 segundos: qué mira el cliente en ese instante", angulo: "titular, prueba y botón: el triángulo de la primera impresión", img: "a glowing website screen emerging from darkness with three golden spotlights hitting its key sections, dramatic studio atmosphere, cinematic depth, photographic detail" },
  { id: "web-boton-llamada", tema: "El botón que tu web necesita y casi ninguna pone bien", angulo: "una sola acción principal, visible, sin competir con diez más", img: "a single glowing golden button floating in a dark minimal space with a soft light beam on it, surrounded by faded grey buttons in shadow, cinematic macro photography" },
  { id: "web-movil-primero", tema: "Tu cliente te visita desde el móvil: tu web, ¿lo sabe?", angulo: "diseñar para el pulgar, no para el monitor del diseñador", img: "hands holding a smartphone with a beautifully glowing website on screen, dark cozy evening ambiance, warm golden screen light on the fingers, photographic realism" },
  { id: "web-velocidad", tema: "Cada segundo de carga te cuesta clientes (y es medible)", angulo: "la velocidad como factor de ventas, no de tecnología", img: "a glowing speedometer made of golden light on a dark dashboard, needle rising, motion blur light trails behind, dramatic automotive-style photography" },
  { id: "web-fotos-reales", tema: "Fotos de stock que parecen de stock: el error que delata tu web", angulo: "imágenes que construyen confianza frente a imágenes de relleno", img: "a glowing framed photograph of a real workshop on a dark wall beside a faded generic stock photo frame, spotlight comparing them, museum-like dramatic lighting" },
  { id: "web-texto-cliente", tema: "Tu web habla de ti; debería hablar de tu cliente", angulo: "cambiar el 'nosotros somos' por el 'usted consigue'", img: "a glowing mirror on a dark elegant wall reflecting a smiling customer instead of the viewer, golden accent lighting, surreal photographic composition" },
  { id: "web-prueba-social", tema: "Sin prueba social, tu web es solo un discurso", angulo: "reseñas, logos, números y casos: lo que convierte escepticismo en llamada", img: "golden testimonial cards floating like constellations around a glowing smartphone, dark space atmosphere, elegant bokeh, cinematic wide shot" },
  { id: "web-estructura-pagina", tema: "El orden de las secciones vende: la anatomía de una landing que convierte", angulo: "problema, solución, prueba, acción: el esqueleto ganador", img: "glowing architectural blueprint lines forming a website layout on a dark drafting table, golden ruler and pencil beside, dramatic overhead light, engineering atmosphere" },
  { id: "web-confianza-visual", tema: "La confianza se ve antes de leerse: diseño que da seguridad", angulo: "tipografía, espacio y acabado: por qué lo premium vende más", img: "an elegant dark business card with gold foil edges on black velvet, dramatic side lighting revealing texture, luxury product photography, macro detail" },
  { id: "web-rediseño-señales", tema: "5 señales de que tu web pide un rediseño a gritos", angulo: "fechas viejas, sin móvil, sin acción clara: el diagnóstico rápido", img: "an old dusty computer monitor with a faded website cracking like dry paint, a golden light beam breaking through from the right, dramatic contrast, cinematic detail" },
  { id: "web-copy-titular", tema: "El titular de tu web: la frase que decide si el resto se lee", angulo: "beneficio claro en una línea, no juegos de palabras", img: "a glowing golden headline floating above a dark printing press, letters made of light, dramatic ink-and-gold atmosphere, macro typography photography" },
  { id: "web-mantenimiento-valor", tema: "Una web sin mantenimiento se devalúa cada mes", angulo: "el activo que se cuida frente al gasto que se olvida", img: "a wilting plant beside a thriving golden plant on a dark windowsill, one in shadow and one in warm light, symbolic photographic comparison, cinematic tones" },

  /* ===== D. Automatización del negocio ===== */
  { id: "auto-que-es", tema: "Automatizar no es robotizar: qué significa de verdad para tu negocio", angulo: "sistemas que hacen lo repetitivo para que tú hagas lo importante", img: "golden gears and circuits interweaving with organic vine leaves on a dark elegant surface, harmony of machine and nature, macro photography, dramatic lighting" },
  { id: "auto-tareas-repetidas", tema: "Las 7 tareas que repites cada semana y una máquina haría gratis", angulo: "inventario honesto de tiempo perdido: responder, agendar, publicar, perseguir", img: "a loop of golden repetitive tasks shown as glowing circular arrows around a tired business owner silhouette, dark studio, cinematic concept photography" },
  { id: "auto-empezar-poco", tema: "Automatiza una sola cosa este mes (y mira lo que pasa)", angulo: "el primer sistema es el que engancha: empieza por el dolor más claro", img: "a single golden domino piece starting to fall toward a long line of pieces in darkness, chain reaction about to begin, dramatic spotlight, macro detail" },
  { id: "auto-coste-no-hacer", tema: "Lo que te cuesta NO automatizar (aunque no lo veas en el banco)", angulo: "horas, clientes perdidos y oportunidades: el coste invisible", img: "golden sand slipping through an hourglass onto a dark executive desk scattered with unanswered message notifications, dramatic chiaroscuro lighting" },
  { id: "auto-sin-programadores", tema: "Ya no hace falta un departamento de sistemas para automatizar", angulo: "la IA y las herramientas actuales lo ponen al alcance de cualquier pyme", img: "a small shop owner confidently touching a glowing holographic control panel floating over his counter, warm neighborhood store light, cinematic realism" },
  { id: "auto-proceso-caos", tema: "Automatizar el caos solo te da caos automático", angulo: "primero el proceso claro, después la máquina", img: "tangled golden threads being combed into elegant straight lines of light by a metallic comb, dark background, macro photography, symbolic order from chaos" },
  { id: "auto-error-humano", tema: "El error humano que te cuesta clientes y una máquina no comete", angulo: "olvidos, retrasos y malos días: la consistencia como ventaja", img: "a flawless golden robotic hand placing perfect chess pieces on a dark board while a human hand trembles nearby, dramatic spotlight, photographic symbolism" },
  { id: "auto-escalar-sin-contratar", tema: "Crecer sin contratar: la palanca que tienes y no usas", angulo: "cuando el sistema absorbe el volumen, el negocio escala sin dolor", img: "a small golden tree growing into a large luminous tree inside a glass dome, roots of light spreading across a dark surface, cinematic growth metaphor" },
  { id: "auto-miedo-empleados", tema: "Qué les dices a tus empleados cuando llega la automatización", angulo: "la máquina quita lo tedioso, no lo valioso", img: "a warm handshake between a human hand and a glowing holographic hand over a dark office desk, trust atmosphere, golden accent light, photographic realism" },
  { id: "auto-medir-retorno", tema: "Cómo saber si tu automatización está funcionando de verdad", angulo: "tres señales simples: horas, respuestas y ventas", img: "a glowing dashboard of golden gauges and dials floating above a dark mahogany desk, elegant executive atmosphere, reflections on polished wood" },
  { id: "auto-clientes-mientras", tema: "Mientras tú atendías a un cliente, tu sistema consiguió dos más", angulo: "el trabajo en segundo plano como ventaja compuesta", img: "a business owner warmly greeting a customer in the foreground while golden light particles form new customer silhouettes in the dark background, cinematic storytelling" },
  { id: "auto-ecosistema-vs-piezas", tema: "Un chatbot suelto no es un ecosistema", angulo: "web, IA, contenido y reseñas trabajando como un solo organismo", img: "four glowing golden puzzle pieces connecting mid-air forming a luminous sphere, dark elegant background, dramatic lighting, photographic detail" },

  /* ===== E. Blogs, SEO y visibilidad ===== */
  { id: "blog-por-que-funciona", tema: "El blog no está muerto: está abandonado (y esa es tu ventaja)", angulo: "cada artículo es un vendedor que trabaja años sin cobrar", img: "an old typewriter on a dark desk sprouting glowing golden pages that float upward like leaves, warm desk lamp light, cinematic magical realism" },
  { id: "blog-google-premia", tema: "Lo que Google premia hoy: constancia y utilidad, no trucos", angulo: "publicar respuestas útiles cada semana supera a cualquier atajo", img: "a golden lighthouse beam sweeping over a dark ocean guiding a small boat to shore, dramatic night seascape, cinematic wide shot" },
  { id: "blog-preguntas-clientes", tema: "Tus clientes ya escriben tus artículos: solo tienes que escuchar", angulo: "cada pregunta que te hacen es un título que Google busca", img: "glowing question marks transforming into golden written pages above a dark meeting table, elegant study atmosphere, photographic surrealism" },
  { id: "blog-articulo-que-vende", tema: "Un artículo que vende no parece un anuncio", angulo: "enseñar primero, vender después: la fórmula de la confianza", img: "an open elegant book with golden light flowing from its pages into a smartphone beside it, dark mahogany desk, warm cinematic glow" },
  { id: "blog-constancia-frecuencia", tema: "Publicar dos veces por semana: el ritmo que cambia un negocio", angulo: "pequeño y constante gana a grande y esporádico", img: "a metronome with golden details ticking steadily on a dark piano, sheet music glowing softly, dramatic side lighting, photographic stillness" },
  { id: "blog-ia-contenido", tema: "Cómo la IA escribe artículos que no suenan a IA", angulo: "guiar la máquina con tu experiencia y tu tono", img: "a human hand and a translucent holographic hand writing together on the same glowing page, dark writer's desk, warm golden light, cinematic collaboration" },
  { id: "blog-seo-local", tema: "Aparecer en tu ciudad: el SEO local que sí puedes ganar", angulo: "no compites con Amazon, compites con el de tu barrio", img: "a glowing golden map pin standing tall on a dark miniature city model, surrounding pins dimmer, dramatic overhead spotlight, macro photography" },
  { id: "blog-palabras-que-buscan", tema: "Cómo descubrir las palabras exactas que tus clientes escriben en Google", angulo: "piensa como cliente, no como dueño", img: "a golden magnifying glass revealing glowing search words floating over a dark keyboard, macro photography, dramatic light contrast" },
  { id: "blog-enlaces-internos", tema: "El hilo invisible que une tus artículos (y que Google adora)", angulo: "enlazar tus propias páginas guía al lector y al buscador", img: "golden threads of light connecting floating pages like a constellation, dark elegant void, cinematic abstract photography" },
  { id: "blog-contenido-viejo", tema: "Tu contenido envejece: cómo mantenerlo joven sin reescribir todo", angulo: "actualizar supera a abandonar: el blog como jardín, no como museo", img: "a gardener's hands pruning a bonsai tree with golden leaves under warm light, dark greenhouse atmosphere, macro photography, calm cinematic mood" },

  /* ===== F. WhatsApp Business ===== */
  { id: "wa-catalogo", tema: "Tu catálogo dentro de WhatsApp: la tienda que ya está en su bolsillo", angulo: "mostrar productos sin que el cliente salga de la conversación", img: "a smartphone showing a glowing golden product catalog floating above it in holographic cards, dark elegant background, photographic realism" },
  { id: "wa-respuestas-rapidas", tema: "Respuestas rápidas en WhatsApp: parecer grande siendo pequeño", angulo: "plantillas bien escritas que suenan a ti y ahorran horas", img: "lightning-fast golden chat bubbles flying from a smartphone like sparks, dark background with motion blur, energetic photographic style" },
  { id: "wa-etiquetas-organizar", tema: "El truco de las etiquetas: tu WhatsApp ordenado como un embudo de ventas", angulo: "nuevo, interesado, agendado, cliente: saber quién es quién", img: "colorful glowing tags organizing floating chat conversations into neat golden columns, dark space, elegant data visualization photography" },
  { id: "wa-mensaje-ausencia", tema: "El mensaje de ausencia que no espanta al cliente", angulo: "decir 'no estoy' sin decir 'no me importas'", img: "a warm glowing door sign reading open soon hanging in a dark elegant shop entrance, welcoming golden light underneath, cinematic detail" },
  { id: "wa-estados-ventas", tema: "Los estados de WhatsApp: publicidad gratis que tus clientes sí ven", angulo: "24 horas de escaparate diario sin pagar un euro", img: "a smartphone glowing with story circles radiating golden light rings outward into darkness, social ripple effect, photographic elegance" },
  { id: "wa-listas-difusion", tema: "Listas de difusión: hablarle a muchos sin parecer un robot de spam", angulo: "segmentar y personalizar para que cada mensaje parezca individual", img: "golden light rays branching from one source to many small glowing phone screens arranged like a constellation, dark background, cinematic" },
  { id: "wa-perfil-profesional", tema: "Tu perfil de WhatsApp Business es una mini-web: configúralo como tal", angulo: "foto, descripción, horario y catálogo: lo primero que revisa el cliente", img: "a smartphone profile card glowing with golden edges floating above a dark desk, elegant minimal composition, dramatic spotlight" },
  { id: "wa-del-chat-a-la-venta", tema: "Del 'hola, ¿precio?' a la venta: el guion de WhatsApp que convierte", angulo: "responder con estructura, no con improvisación", img: "a golden path of light stepping stones crossing dark water from a chat bubble to a glowing handshake, cinematic symbolic photography" },

  /* ===== G. Google Maps y presencia local ===== */
  { id: "gmaps-ficha-completa", tema: "La ficha de Google perfecta: cada campo que dejas vacío es un cliente que se va", angulo: "servicios, atributos, fotos y horarios: el checklist completo", img: "a glowing checklist of golden light floating beside a map pin on a dark elegant desk, dramatic overhead light, photographic detail" },
  { id: "gmaps-fotos-venden", tema: "Las fotos de tu ficha venden más que tu cartel", angulo: "qué fotografiar, cuántas subir y con qué frecuencia", img: "a camera lens capturing a glowing golden storefront, the photo materializing mid-air as a bright map listing, cinematic transition effect" },
  { id: "gmaps-posts-semanales", tema: "Publicar en tu ficha de Google cada semana (sí, también es una red social)", angulo: "novedades y ofertas que mantienen tu ficha viva y visible", img: "a map pin glowing brighter with each golden pulse like a heartbeat, dark city map background, rhythmic cinematic light" },
  { id: "gmaps-tres-del-mapa", tema: "Por qué solo salen 3 negocios en el mapa (y cómo colarte)", angulo: "proximidad, relevancia y autoridad: las tres palancas reales", img: "three golden thrones of light on a dark map with a fourth contender rising from the shadows, dramatic theatrical lighting" },
  { id: "gmaps-categoria-correcta", tema: "La categoría de tu ficha decide quién te encuentra", angulo: "elegir bien la principal y las secundarias cambia tu tráfico", img: "a golden signpost with multiple direction arrows on a dark crossroads, one arrow glowing brighter than the rest, cinematic guidance scene" },
  { id: "gmaps-preguntas-respuestas", tema: "La sección de preguntas de tu ficha: la pones tú o la pondrá otro", angulo: "sembrar tus propias preguntas con respuestas perfectas", img: "glowing question bubbles being answered by golden light responses above a dark smartphone map, photographic surrealism" },
  { id: "gmaps-estadisticas", tema: "Tu ficha de Google te dice cuánta gente te encontró: aprende a leerla", angulo: "llamadas, direcciones y búsquedas: datos gratis que nadie mira", img: "a glowing analytics chart rising like a golden skyline from a smartphone map, dark executive atmosphere, cinematic data visualization" },
  { id: "gmaps-cita-directa", tema: "Que te reserven directo desde Google: el botón que casi nadie activa", angulo: "reservas y pedidos sin que el cliente salga del mapa", img: "a golden calendar button glowing on a dark map interface, a finger of light about to tap it, macro photographic detail" },
  { id: "gmaps-atributos", tema: "WiFi, terraza, parking: los atributos que deciden una visita", angulo: "los detalles prácticos que el cliente filtra antes de elegir", img: "small glowing golden icons floating above a dark storefront like helpful spirits, warm welcoming light, cinematic charm" },
  { id: "gmaps-multi-sede", tema: "¿Varias sedes? Cada una necesita su propia estrategia en el mapa", angulo: "una ficha por ubicación, contenido local para cada una", img: "multiple golden map pins connected by threads of light over a dark regional map, network atmosphere, cinematic aerial view" },

  /* ===== H. IA aplicada a la pyme ===== */
  { id: "ia-sin-miedo", tema: "La IA no viene a por tu negocio: viene a por tus tareas aburridas", angulo: "desmitificar con ejemplos cotidianos de negocio local", img: "a friendly glowing holographic assistant handing a golden key to a relaxed shop owner, warm dark interior, cinematic trust atmosphere" },
  { id: "ia-redactar-emails", tema: "Emails en dos minutos: la IA como tu redactor personal", angulo: "propuestas, respuestas y seguimientos sin bloqueo de pantalla en blanco", img: "glowing golden letters assembling themselves into an elegant email on a dark screen, writer's desk ambiance, photographic detail" },
  { id: "ia-analizar-competencia", tema: "Espía a tu competencia con IA (legalmente y sin moverte de la silla)", angulo: "resumir sus webs, reseñas y ofertas en minutos", img: "a golden magnifying glass hovering over glowing miniature storefronts on a dark table, detective atmosphere, dramatic side light" },
  { id: "ia-imagenes-marca", tema: "Imágenes de marca sin fotógrafo: cuándo la IA sirve y cuándo no", angulo: "bocetos, ideas y fondos sí; tu producto real, siempre foto real", img: "a glowing holographic canvas being painted with golden light strokes beside a real product photograph, dark studio, cinematic contrast" },
  { id: "ia-atencion-hibrida", tema: "El modelo híbrido: IA para lo repetido, humano para lo delicado", angulo: "diseñar el reparto de trabajo perfecto", img: "a balancing scale of golden light with robotic and human elements in perfect equilibrium, dark elegant void, symbolic photography" },
  { id: "ia-formar-equipo", tema: "Tu equipo usando IA en una semana: el plan realista", angulo: "empezar por tres usos concretos, no por un curso eterno", img: "a team of silhouettes climbing glowing golden steps of light together, dark background, upward cinematic composition" },
  { id: "ia-errores-comunes", tema: "Los 5 errores al usar IA en tu negocio (y cómo evitarlos)", angulo: "copiar sin revisar, prompts vagos, datos sensibles: los clásicos", img: "golden warning signs floating around a glowing path in a dark corridor, careful navigation atmosphere, cinematic caution" },
  { id: "ia-coste-real", tema: "Cuánto cuesta de verdad poner IA en una pyme", angulo: "desde gratis hasta serio: los niveles y qué da cada uno", img: "golden coins transforming into glowing light tools on a dark workbench, value metaphor, macro photography, warm tones" },
  { id: "ia-voz-marca", tema: "Entrenar a la IA con tu voz de marca: el documento que lo cambia todo", angulo: "cómo suenas, qué dices y qué nunca dirías", img: "a glowing golden soundwave transforming into written words on dark paper, voice becoming text, cinematic audio visualization" },
  { id: "ia-reuniones-resumen", tema: "Reuniones que se resumen solas: el fin de '¿qué habíamos quedado?'", angulo: "transcribir, resumir y asignar: la reunión que deja tareas claras", img: "glowing golden notes emerging from a meeting table like butterflies, dark conference room, cinematic magic realism" },
  { id: "ia-propuestas-comerciales", tema: "Propuestas comerciales en minutos que parecen de agencia cara", angulo: "estructura, diseño y personalización con ayuda de IA", img: "an elegant golden document assembling itself page by page above a dark executive desk, premium proposal aesthetic, cinematic" },
  { id: "ia-datos-decisiones", tema: "Tus datos hablan: la IA como traductora de tu negocio", angulo: "preguntarle a tus números en lenguaje normal", img: "golden numbers and charts flowing into a glowing ear-shaped light formation, dark background, symbolic data translation, cinematic" },

  /* ===== I. Ventas y conversión ===== */
  { id: "venta-embudo-simple", tema: "El embudo de ventas explicado con tu negocio de siempre", angulo: "descubrir, confiar, comprar: sin diagramas de gurú", img: "a golden funnel of light with glowing customers flowing through it into a welcoming shop door, dark background, cinematic clarity" },
  { id: "venta-seguimiento", tema: "El seguimiento: donde están el 80% de las ventas que pierdes", angulo: "el segundo y tercer contacto que nadie hace", img: "golden footsteps of light following a path toward a warm glowing doorway, persistence metaphor, dark cinematic scene" },
  { id: "venta-propuesta-ganadora", tema: "La propuesta que no se puede ignorar: estructura de 5 partes", angulo: "problema, plan, prueba, precio y próximo paso", img: "five glowing golden pillars supporting an elegant document of light, dark architectural space, cinematic structure metaphor" },
  { id: "venta-precio-valor", tema: "Cuando te dicen 'eres caro' es que no han visto el valor", angulo: "comunicar lo que incluye antes de defender el número", img: "a golden scale weighing a glowing diamond against plain coins, dark luxurious background, cinematic value metaphor" },
  { id: "venta-objeciones-frecuentes", tema: "Las 6 objeciones que se repiten en todos los negocios", angulo: "precio, tiempo, pensarlo: respuestas preparadas ganan ventas", img: "six glowing golden shields blocking arrow-like objections of shadow, dark battlefield elegance, cinematic defense metaphor" },
  { id: "venta-urgencia-honesta", tema: "Crear urgencia sin mentir: escasez real y plazos reales", angulo: "la diferencia entre presionar y facilitar la decisión", img: "an elegant golden hourglass with limited glowing sand beside an honest open door of light, dark background, cinematic honesty" },
  { id: "venta-cliente-ideal", tema: "Venderle a todos es venderle a nadie", angulo: "definir tu cliente ideal cambia tus textos, tus precios y tu agenda", img: "a golden spotlight illuminating one specific silhouette in a dark crowd, focus metaphor, dramatic theatrical lighting" },
  { id: "venta-llamada-descubrimiento", tema: "La primera llamada con un cliente: preguntas que venden solas", angulo: "escuchar bien es la mitad del cierre", img: "two glowing speech bubbles intertwining into a golden knot of agreement, dark elegant void, cinematic dialogue metaphor" },
  { id: "venta-cross-sell", tema: "Tu cliente ya confía: la venta adicional que no molesta", angulo: "ofrecer lo siguiente en el momento de máxima satisfacción", img: "a golden gift box glowing beside a completed handshake of light, dark celebratory atmosphere, cinematic upsell metaphor" },
  { id: "venta-referidos-sistema", tema: "Los referidos no llegan solos: el sistema que los provoca", angulo: "pedirlos en el momento justo con el incentivo correcto", img: "a golden ripple effect expanding from one happy customer silhouette to many others, dark water surface, cinematic chain reaction" },

  /* ===== J. Productividad del dueño ===== */
  { id: "prod-semana-dueno", tema: "La semana ideal del dueño de negocio (segunda versión: con sistemas)", angulo: "antes y después de automatizar: el mismo lunes, otra vida", img: "a split scene: chaotic dark paperwork on the left, a serene golden organized desk on the right, cinematic transformation" },
  { id: "prod-decisiones-fatiga", tema: "Decides demasiado: la fatiga que frena tu negocio", angulo: "cada decisión pequeña roba energía a las grandes", img: "a silhouette at a crossroads with a hundred small glowing arrows pointing everywhere, one golden path shining clearly ahead, cinematic clarity metaphor" },
  { id: "prod-bloques-tiempo", tema: "Bloques de tiempo: el calendario que protege tu hora más valiosa", angulo: "agrupar lo repetitivo y proteger lo estratégico", img: "glowing golden blocks of time stacking neatly like bricks building a fortress, dark background, architectural light, cinematic" },
  { id: "prod-email-dos-veces", tema: "Revisa el correo dos veces al día (y recupera tu negocio)", angulo: "el correo como tarea, no como estado permanente", img: "an inbox envelope of golden light opening only twice like a flower blooming, dark time-lapse atmosphere, cinematic discipline" },
  { id: "prod-delegar-sistema", tema: "Delegar no es soltar: es documentar el cómo", angulo: "el manual de una página que libera tu cabeza", img: "a glowing golden instruction manual page handing tasks to waiting hands of light, dark office elegance, cinematic delegation" },
  { id: "prod-manana-ganada", tema: "La primera hora del día decide toda la semana", angulo: "rutina de apertura para dueños: sin móvil, con prioridades", img: "golden sunrise light entering a dark office through blinds onto an organized desk with three priority cards, cinematic morning" },
  { id: "prod-herramientas-minimas", tema: "Las 5 herramientas que tu negocio necesita (y las 15 que le sobran)", angulo: "menos apps, más sistema: la simplificación tecnológica", img: "five glowing golden tools on a dark workbench with faded redundant tools dissolving into shadow, cinematic minimalism with warmth" },
  { id: "prod-revision-semanal", tema: "La revisión semanal de 30 minutos que ordena todo lo demás", angulo: "viernes: números, pendientes y plan de la semana siguiente", img: "a golden compass resting on an elegant dark weekly planner, warm lamp glow, preparation atmosphere, cinematic still life" },

  /* ===== K. Datos y números del negocio ===== */
  { id: "datos-tres-numeros", tema: "Los 3 números que un dueño debe mirar cada semana", angulo: "clientes nuevos, ticket medio y repetición: lo esencial", img: "three glowing golden dials on a dark elegant dashboard, simplicity in design, warm accent lighting, photographic clarity" },
  { id: "datos-cliente-vale-mas", tema: "Cuánto vale un cliente de verdad (la cifra que cambia tus decisiones)", angulo: "valor de vida del cliente explicado sin fórmulas", img: "a golden tree growing from a single coin with branches of glowing light spreading wide, dark soil, cinematic growth metaphor" },
  { id: "datos-que-no-importan", tema: "Métricas de vanidad: los números bonitos que no pagan facturas", angulo: "seguidores y visitas frente a llamadas y ventas", img: "shiny but hollow golden bubbles floating above a solid glowing foundation stone, dark background, cinematic substance metaphor" },
  { id: "datos-origen-clientes", tema: "¿De dónde vienen tus clientes? Si no lo sabes, estás tirando dinero", angulo: "preguntar y apuntar: la analítica del negocio de barrio", img: "golden light trails from different directions converging into a shop door on a dark map, origin visualization, cinematic" },
  { id: "datos-excel-vs-panel", tema: "Del Excel al panel automático: cuándo dar el salto", angulo: "señales de que tu hoja de cálculo ya se quedó pequeña", img: "a glowing spreadsheet transforming into an elegant golden dashboard of light, dark transformation scene, cinematic evolution" },
  { id: "datos-predecir-temporada", tema: "Tus datos del año pasado predicen tu próxima temporada", angulo: "anticipar picos y valles para no improvisar", img: "golden waves of light forming seasonal patterns over a dark calendar, forecasting atmosphere, cinematic data art" },
  { id: "datos-coste-captacion", tema: "Cuánto te cuesta conseguir un cliente (y por qué deberías saberlo)", angulo: "publicidad, tiempo y esfuerzo: el coste completo", img: "a golden fishing rod of light catching a glowing customer silhouette from a dark sea, acquisition metaphor, cinematic" },
  { id: "datos-errores-medir", tema: "Medir mal es peor que no medir", angulo: "tres errores clásicos al mirar los números del negocio", img: "a crooked golden ruler measuring a glowing object incorrectly beside a straight one measuring correctly, dark workshop, cinematic" },

  /* ===== L. Citas y agenda ===== */
  { id: "citas-agenda-llena", tema: "La agenda llena sin perseguir a nadie", angulo: "cuando reservar es fácil, la gente reserva", img: "a glowing golden calendar filling itself with bright appointments like stars appearing, dark elegant void, cinematic automation" },
  { id: "citas-ausencias", tema: "El plantón: cuánto te cuesta y cómo reducirlo a casi cero", angulo: "recordatorios automáticos y confirmaciones: la vacuna contra el no-show", img: "an empty chair in a dark waiting room with a golden reminder light pulsing above it, prevention atmosphere, cinematic mood" },
  { id: "citas-recordatorios", tema: "El recordatorio perfecto: cuándo enviarlo y qué decir", angulo: "48 horas, 24 horas y el mensaje que sí confirma", img: "golden notification bells ringing softly at timed intervals along a glowing timeline, dark space, rhythmic cinematic composition" },
  { id: "citas-reserva-online", tema: "Que te reserven mientras duermes: la agenda online sin dolores", angulo: "huecos reales, confirmación inmediata, cero llamadas perdidas", img: "a smartphone glowing with an open calendar while its owner sleeps peacefully in the dark background, moonlight and warm screen glow" },
  { id: "citas-horarios-inteligentes", tema: "Tus horarios no son para ti: son para tu cliente", angulo: "la franja que nadie ofrece y todos quieren", img: "a golden clock face morphing to fit around a customer's silhouette, dark elegant background, flexible time metaphor, cinematic" },
  { id: "citas-lista-espera", tema: "La lista de espera automática: el hueco cancelado que se rellena solo", angulo: "aviso inmediato al siguiente interesado", img: "glowing golden names on a waiting list ascending like elevators of light as slots open, dark vertical space, cinematic motion" },
  { id: "citas-pago-anticipado", tema: "Cobrar la señal al reservar: menos plantones, más compromiso", angulo: "la reserva con pago parcial como filtro de seriedad", img: "a golden handshake of light with a coin of light exchanged mid-shake, trust and commitment atmosphere, dark cinematic scene" },
  { id: "citas-agenda-equipo", tema: "Una agenda para todo el equipo: el fin de los cruces", angulo: "quién atiende a quién, cuándo y dónde: visible para todos", img: "multiple glowing golden calendars merging into one master calendar of light, dark organizational elegance, cinematic harmony" },

  /* ===== M. Redes sociales con cabeza ===== */
  { id: "rrss-donde-estar", tema: "No necesitas estar en todas las redes: necesitas estar donde está tu cliente", angulo: "una red bien llevada gana a cuatro abandonadas", img: "a single golden spotlight illuminating one stage among many dark stages, focus and choice metaphor, theatrical cinematic lighting" },
  { id: "rrss-contenido-sistema", tema: "Un mes de contenido en una tarde: el sistema de lotes", angulo: "grabar, recortar y programar: producción en serie para pymes", img: "golden video frames on a production line of light being stamped and scheduled, dark factory elegance, cinematic assembly metaphor" },
  { id: "rrss-video-corto", tema: "El video corto: el formato que más alcance da hoy a un negocio local", angulo: "30 segundos, una idea, tu cara o tu producto", img: "a smartphone filming a glowing golden moment in a workshop, the video radiating light rings outward, dark cinematic energy" },
  { id: "rrss-de-red-a-web", tema: "Las redes prestan, tu web queda: por qué tu casa es tu web", angulo: "convertir seguidores en visitas y visitas en clientes", img: "golden light flowing from social media icons into a solid glowing website foundation, dark background, cinematic ownership metaphor" },
  { id: "rrss-perfil-que-vende", tema: "Tu perfil de Instagram es tu nuevo escaparate: móntalo como tal", angulo: "bio clara, destacadas ordenadas y enlace que convierte", img: "a glowing shop window display made of golden light inside a smartphone screen, dark street, cinematic window-shopping scene" },
  { id: "rrss-constancia-vs-viral", tema: "Olvida el viral: la constancia aburrida es la que vende", angulo: "publicar cada semana supera al milagro de un día", img: "a steady golden tortoise of light overtaking a flashy but fading comet, dark racetrack, cinematic fable metaphor" },
  { id: "rrss-comentarios-ventas", tema: "Los comentarios son el nuevo mostrador: respóndelos como tal", angulo: "cada comentario respondido es una venta empezada", img: "glowing comment bubbles rising like golden lanterns from a smartphone, warm conversation atmosphere, dark cinematic charm" },
  { id: "rrss-metricas-reales", tema: "Guardados y compartidos: las métricas que de verdad importan", angulo: "el like es educación; el guardado es intención", img: "golden bookmark and share icons glowing brightly among faded heart icons, dark space, cinematic priority metaphor" },

  /* ===== N. Competencia y diferenciación ===== */
  { id: "comp-por-que-te-eligen", tema: "¿Por qué te eligen a ti? Si no lo sabes, tus clientes tampoco", angulo: "la respuesta en una frase: tu diferencia real", img: "a golden spotlight on a single distinct silhouette standing apart from a uniform crowd, dark stage, cinematic uniqueness" },
  { id: "comp-copiar-mejorar", tema: "Copiar a tu competencia te hace invisible: mejórala en lo que ella ignora", angulo: "sus quejas repetidas son tu carta de presentación", img: "a golden chisel refining a rough stone statue into an elegant glowing figure, dark workshop, cinematic craftsmanship" },
  { id: "comp-guerra-precios", tema: "La guerra de precios la gana quien puede bajar más: tú no quieres ganarla", angulo: "competir por valor, experiencia y confianza", img: "two racing boats cutting prices leaving wreckage, a third golden boat sailing a different calm route toward sunrise, dark sea, cinematic" },
  { id: "comp-nicho-local", tema: "Ser el mejor de tu zona para algo concreto", angulo: "especializarse localmente es más rentable que generalizar", img: "a golden flag of light planted on a specific neighborhood rooftop, dark city panorama, cinematic territory metaphor" },
  { id: "comp-vigilancia-sana", tema: "Revisar a tu competencia una vez al mes: ni obsesión ni ceguera", angulo: "qué mirar: precios, reseñas, novedades y tono", img: "a golden periscope of light rising calmly from a dark submarine, measured observation atmosphere, cinematic restraint" },
  { id: "comp-experiencia-moat", tema: "La experiencia que das no se puede copiar con un cartel", angulo: "procesos y trato: la ventaja defensible", img: "a golden moat of light protecting a warm glowing castle shop, dark medieval elegance, cinematic defense metaphor" },
  { id: "comp-alianzas-locales", tema: "Aliarte con el negocio de al lado: la estrategia que nadie usa", angulo: "clientes compartidos, promociones cruzadas, cero coste", img: "two neighboring storefronts connected by a glowing golden bridge of light, dark street, cinematic partnership atmosphere" },
  { id: "comp-velocidad-respuesta", tema: "Responder primero es el nuevo 'ser mejor'", angulo: "en negocios locales, la velocidad gana a la fama", img: "a golden lightning bolt of light reaching a customer's door before slower shadows arrive, dark race scene, cinematic speed" },

  /* ===== O. Experiencia del cliente ===== */
  { id: "exp-primer-contacto", tema: "Los primeros 30 segundos con un cliente nuevo", angulo: "cómo suena tu saludo, tu chat y tu escaparate digital", img: "a warm golden doorway of first impression opening with welcoming light, dark threshold, cinematic hospitality" },
  { id: "exp-detalles-memorables", tema: "El detalle que hace que te recuerden (y te recomienden)", angulo: "pequeños gestos sistematizables, no heroicidades", img: "a small golden gift ribbon glowing on an ordinary package, dark elegant table, cinematic detail focus, macro photography" },
  { id: "exp-queja-regalo", tema: "El cliente que se queja te está haciendo un regalo", angulo: "cada queja bien gestionada es un cliente recuperado y mejorado", img: "a dark thorny rose transforming into a golden blooming flower in caring hands, cinematic transformation metaphor" },
  { id: "exp-promesas-cumplidas", tema: "Vende menos, cumple más: la fórmula antigua que siempre funciona", angulo: "prometer con margen y sorprender con el extra", img: "a golden promise seal of light being stamped on a contract that glows brighter than expected, dark elegant desk, cinematic trust" },
  { id: "exp-postventa-olvidada", tema: "La postventa: la mina de oro que casi nadie trabaja", angulo: "el mensaje a los 7 días que genera reseñas, referidos y recompra", img: "a golden thread of light connecting a completed sale to future glowing opportunities, dark space, cinematic continuity" },
  { id: "exp-personalizar-escala", tema: "Personalizar sin morir en el intento: plantillas con alma", angulo: "nombre, contexto y detalle: el sistema del trato cercano", img: "golden letters being individually stamped with unique seals of light on a production line, dark elegant factory, cinematic craft" },
  { id: "exp-tiempo-espera", tema: "La espera percibida: por qué 5 minutos informados duelen menos que 2 a oscuras", angulo: "comunicar el estado de todo reduce la ansiedad del cliente", img: "a golden progress bar of light illuminating a dark waiting room where a calm customer reads, cinematic patience metaphor" },
  { id: "exp-cierre-impecable", tema: "El final de la venta es el principio de la siguiente", angulo: "despedir bien, agradecer y dejar la puerta abierta", img: "an elegant golden doorway closing gently with light spilling through a window that opens ahead, cinematic cycle metaphor" },

  /* ===== P. Errores y lecciones ===== */
  { id: "error-web-como-folleto", tema: "Tu web no es un folleto: es tu vendedor de guardia", angulo: "el folleto informa; el vendedor consigue llamadas", img: "a dusty paper brochure in shadow beside a glowing golden salesperson silhouette extending a hand, dark contrast scene, cinematic" },
  { id: "error-contestar-cuando-puedo", tema: "'Ya le contesto cuando pueda': la frase que regala clientes a tu competencia", angulo: "la lentitud como decisión estratégica accidental", img: "golden sand slipping through fingers of light while a customer silhouette walks away into darkness, cinematic loss metaphor" },
  { id: "error-tecnologia-sin-plan", tema: "Comprar herramientas sin plan: el cementerio de suscripciones", angulo: "primero el proceso, luego la herramienta que lo ejecuta", img: "glowing but abandoned subscription cards piled like tombstones in a dark graveyard, one golden compass glowing above, cinematic warning" },
  { id: "error-hacer-todo-solo", tema: "El síndrome del dueño todoterreno: la trampa de los 30.000 al año", angulo: "tu hora vale más que la tarea que te niegas a soltar", img: "a juggler silhouette struggling with too many dark balls while golden helping hands wait unused beside him, cinematic overload" },
  { id: "error-desaparecer-google", tema: "Desaparecer de Google es más fácil de lo que crees", angulo: "ficha abandonada, web rota, sin contenido: el declive silencioso", img: "a glowing shop light dimming slowly on a dark street while neighbors shine brighter, cinematic fade, cautionary atmosphere" },
  { id: "error-contenido-irregular", tema: "El blog que nació en enero y murió en febrero", angulo: "por qué la motivación falla y el sistema no", img: "a wilted golden plant in an abandoned pot beside a thriving one on an automatic watering system, dark greenhouse, cinematic contrast" },
  { id: "error-medir-nada", tema: "Volar a ciegas: dirigir tu negocio sin saber qué funciona", angulo: "no necesitas big data, necesitas tres cifras", img: "a pilot silhouette flying through dark clouds with a cracked compass, a golden dashboard appearing ahead, cinematic guidance" },
  { id: "error-cliente-incomodo", tema: "Ignorar al cliente incómodo te cuesta diez contentos", angulo: "el que se queja en público y no recibe respuesta", img: "a single dark storm cloud over one customer casting shadows on ten golden happy silhouettes nearby, cinematic ripple effect" },

  /* ===== Q. Retorno e inversión (ROI) ===== */
  { id: "roi-web-inversion", tema: "Tu web: ¿gasto o inversión? La diferencia está en lo que recupera", angulo: "una web que trae un cliente al mes ya se paga sola", img: "a golden seed growing into a money tree of light on dark fertile soil, investment growth metaphor, cinematic prosperity" },
  { id: "roi-hora-dueno", tema: "Calcula lo que vale tu hora: el número que ordena tus decisiones", angulo: "cuando sabes que tu hora vale 50, dejas de hacer tareas de 5", img: "a golden hourglass with coins of light instead of sand, dark executive desk, cinematic time-value metaphor" },
  { id: "roi-automatizacion-paga", tema: "La automatización se paga sola: el cálculo en 3 líneas", angulo: "horas recuperadas por semana por valor de tu hora", img: "a golden abacus with glowing beads calculating returns on a dark accountant desk, warm lamp light, cinematic precision" },
  { id: "roi-cliente-recuperado", tema: "Recuperar un cliente perdido cuesta 5 veces menos que conseguir uno nuevo", angulo: "la base de datos dormida que tienes y no usas", img: "a golden phoenix of light rising from old customer records, dark archive room, cinematic revival metaphor" },
  { id: "roi-contenido-activo", tema: "Un artículo es un activo: cómo se revaloriza con el tiempo", angulo: "lo que publicas hoy vende dentro de dos años", img: "golden pages stacking into a growing vault of light, dark treasury atmosphere, cinematic compound growth" },
  { id: "roi-publicidad-vs-sistema", tema: "Publicidad que paras y se acaba, sistema que construyes y queda", angulo: "alquiler de atención frente a propiedad de atención", img: "a rented spotlight fading beside a self-built golden lighthouse standing permanently, dark coastline, cinematic ownership metaphor" },
  { id: "roi-cuando-invertir", tema: "Cuándo invertir en tu negocio digital (y cuándo esperar)", angulo: "señales de madurez: demanda estable, proceso claro, capacidad justa", img: "a golden gateway of light opening at the right moment on a dark path, timing atmosphere, cinematic decision point" },
  { id: "roi-medir-web", tema: "Cómo saber si tu web está ganando dinero o solo existiendo", angulo: "llamadas, formularios y ventas atribuidas: la cuenta simple", img: "a golden scale of light balancing website costs against flowing customer revenue, dark accounting elegance, cinematic balance" },

  /* ===== R. Sectores concretos ===== */
  { id: "sector-clinicas", tema: "Clínicas y consultas: la agenda que se llena sola", angulo: "reserva online, recordatorios y reseñas: el trío que transforma una clínica", img: "an elegant clinic reception with a glowing golden appointment book filling itself, dark warm corridor, cinematic healthcare calm" },
  { id: "sector-restaurantes", tema: "Restaurantes: del '¿hay mesa?' al lleno semanal", angulo: "reservas automáticas, carta digital y reseñas que atraen", img: "a warmly lit restaurant table with a glowing golden reservation card, dark elegant dining room, cinematic gastronomy" },
  { id: "sector-abogados", tema: "Despachos de abogados: confianza antes de la primera llamada", angulo: "contenido que demuestra criterio y una web que filtra casos", img: "an elegant dark law office with golden scales of justice glowing softly beside a modern laptop, cinematic professional trust" },
  { id: "sector-gimnasios", tema: "Gimnasios y entrenadores: la retención empieza antes de la primera clase", angulo: "reserva de clases, seguimiento automático y comunidad", img: "a dark premium gym with golden light tracing a path to glowing class schedules, cinematic athletic atmosphere" },
  { id: "sector-inmobiliarias", tema: "Inmobiliarias: el comprador empieza en Google, no en tu oficina", angulo: "fichas completas, respuestas rápidas y visitas agendadas solas", img: "a glowing golden house key hovering over an elegant dark miniature house model, cinematic real estate atmosphere" },
  { id: "sector-talleres", tema: "Talleres y servicios técnicos: el presupuesto que llega ya cualificado", angulo: "formulario inteligente que pregunta lo justo antes de la visita", img: "an elegant dark workshop with golden diagnostic light scanning a machine, precision atmosphere, cinematic craftsmanship" },
  { id: "sector-academias", tema: "Academias y formación: matrículas mientras enseñas", angulo: "información automática, pruebas de nivel y reservas de plaza", img: "a warm classroom with a glowing golden graduation cap of light above an enrollment form, dark academic elegance, cinematic" },
  { id: "sector-estetica", tema: "Centros de estética y peluquerías: la silla nunca vacía", angulo: "huecos de última hora rellenados automáticamente", img: "an elegant salon chair bathed in warm golden light with a full glowing appointment book beside it, dark beauty atmosphere, cinematic" },
  { id: "sector-veterinarias", tema: "Veterinarias: los recordatorios que salvan la agenda (y la salud de las mascotas)", angulo: "vacunas, revisiones y urgencias bien canalizadas", img: "a warm veterinary consultation room with golden light and a calm pet silhouette, caring atmosphere, cinematic tenderness" },
  { id: "sector-asesorias", tema: "Asesorías y gestorías: dejar de perseguir papeles", angulo: "solicitud automática de documentos y recordatorios de plazos", img: "golden documents of light flying in order into glowing folders, dark office, cinematic organization, elegant bureaucracy tamed" },
  { id: "sector-hoteles", tema: "Hoteles y turismo rural: la reserva directa que te ahorra la comisión", angulo: "web propia, respuestas instantáneas y reseñas trabajadas", img: "a charming rural hotel entrance with a glowing golden key card and warm window lights, dark evening welcome, cinematic hospitality" },
  { id: "sector-ecommerce-local", tema: "Tiendas locales con envío: competir con el gigante sin serlo", angulo: "cercanía, rapidez y trato como ventajas frente al marketplace", img: "a warm local shop with golden delivery packages of light heading out into the neighborhood, dark evening, cinematic David-vs-Goliath" },
  { id: "sector-constructoras", tema: "Constructoras y reformas: el presupuesto que se pide por la web", angulo: "galería de obras, formulario de proyecto y confianza previa", img: "an elegant architectural blueprint glowing with golden lines over a dark drafting table, hard hat beside, cinematic construction" },
  { id: "sector-dentistas", tema: "Dentistas: el miedo al dentista se cura con información y confianza", angulo: "contenido que tranquiliza, reseñas que avalan y cita en dos clics", img: "a calm modern dental office in dark warm tones with a reassuring golden light over the chair, cinematic healthcare serenity" },

  /* ===== S. Marca personal y del negocio ===== */
  { id: "marca-dueno-visible", tema: "Que se vea al dueño: la marca detrás del mostrador", angulo: "la gente compra a personas, no a logotipos", img: "a warm portrait silhouette of a business owner framed by golden light in their own shop, dark intimate atmosphere, cinematic authenticity" },
  { id: "marca-historia", tema: "Tu historia vende: por qué empezaste importa más que tu catálogo", angulo: "la sección 'sobre nosotros' que de verdad conecta", img: "an old photograph glowing with golden nostalgia beside a modern smartphone showing the same shop today, dark desk, cinematic legacy" },
  { id: "marca-coherencia", tema: "La coherencia: que tu web, tu ficha y tu local cuenten lo mismo", angulo: "mismo tono, mismas fotos, misma promesa en cada punto de contacto", img: "three glowing golden mirrors reflecting the same consistent image of a shop, dark elegant space, cinematic brand harmony" },
  { id: "marca-titulo-experto", tema: "Convertirse en 'el experto de tu zona' en 6 meses de contenido", angulo: "publicar lo que sabes posiciona más que cualquier anuncio", img: "a golden podium of light rising on a dark neighborhood stage, a silhouette being recognized, cinematic authority building" },
  { id: "marca-logo-vs-reputacion", tema: "Tu logo no es tu marca: tu reputación sí", angulo: "lo que dicen cuando no estás vale más que tu diseño", img: "a simple logo in shadow beside a glowing constellation of golden reviews forming the true brand shape, dark space, cinematic truth" },
  { id: "marca-fotos-equipo", tema: "Fotos del equipo real: el antídoto contra la desconfianza", angulo: "caras reales superan a cualquier diseño abstracto", img: "warm golden team portraits glowing on a dark elegant wall of a business, human connection atmosphere, cinematic warmth" },
  { id: "marca-promesa-unica", tema: "La promesa de tu negocio en una frase que un niño entienda", angulo: "si no cabe en una frase, no cabe en la cabeza del cliente", img: "a single golden sentence of light engraved on dark stone, simplicity monument, cinematic clarity" },
  { id: "marca-google-vs-instagram", tema: "Dónde construir tu marca si solo tienes tiempo para un sitio", angulo: "para negocios locales, Google pesa más que likes", img: "a golden map pin outweighing social hearts on an elegant dark scale, cinematic priority judgment" },

  /* ===== T. Primeros pasos digitales ===== */
  { id: "pasos-empezar-hoy", tema: "Digitalizar tu negocio: la primera semana, paso a paso", angulo: "día a día: ficha de Google, fotos, primer mensaje automático", img: "seven glowing golden stepping stones of light crossing a dark river, each labeled with progress, cinematic journey start" },
  { id: "pasos-sin-presupuesto", tema: "Qué puedes digitalizar hoy con 0 euros", angulo: "ficha de Google, WhatsApp Business y tres fotos decentes", img: "golden tools of light appearing from thin air onto a dark workbench, resourcefulness atmosphere, cinematic bootstrap" },
  { id: "pasos-orden-correcto", tema: "El orden importa: ficha, web, chatbot, contenido", angulo: "cada capa se apoya en la anterior; saltarse pasos sale caro", img: "golden floors of light building upward like a tower, each level glowing solid before the next appears, dark sky, cinematic foundation" },
  { id: "pasos-miedo-tecnologia", tema: "Si la tecnología te da respeto, empieza por aquí", angulo: "tres pasos que no requieren saber de tecnología", img: "a gentle golden handrail of light guiding someone up dark stairs, supportive atmosphere, cinematic encouragement" },
  { id: "pasos-web-propia-cuando", tema: "¿Cuándo necesitas web propia de verdad?", angulo: "señales: te preguntan por ella, tu competencia la tiene, dependes de terceros", img: "a golden key appearing in a door that was previously just a wall, dark hallway, cinematic opportunity moment" },
  { id: "pasos-elegir-quien-te-ayuda", tema: "Cómo elegir quién te hace la web (sin que te vendan humo)", angulo: "preguntas que delatan al que sabe y al que vende", img: "a golden magnifying glass revealing the true craftsmanship behind glowing proposals on a dark desk, cinematic due diligence" },
  { id: "pasos-30-dias", tema: "Tu negocio transformado en 30 días: el plan realista", angulo: "semana 1 base, semana 2 atención, semana 3 contenido, semana 4 reseñas", img: "a glowing golden 30-day calendar with each week shining in progression, dark elegant void, cinematic transformation plan" },
  { id: "pasos-fotos-con-movil", tema: "Fotos profesionales con tu móvil: la mini-guía de 10 minutos", angulo: "luz de ventana, fondo limpio y horizontal: lo esencial", img: "a smartphone on a small tripod capturing a beautifully lit product by a window, golden natural light, dark room, cinematic tutorial mood" },
  { id: "pasos-primera-venta-digital", tema: "Tu primera venta que llegó sola: cómo se siente y cómo se repite", angulo: "documentar el primer cliente automático para multiplicarlo", img: "a single golden notification of light glowing on a phone at dawn, first light atmosphere, cinematic milestone moment" },
  { id: "pasos-aliado-tecnologico", tema: "No necesitas un informático: necesitas un aliado que hable tu idioma", angulo: "tecnología explicada en euros y horas, no en siglas", img: "two silhouettes shaking hands of golden light across a dark table, one technical one business, bridge atmosphere, cinematic partnership" },

  /* ===== U. Tendencias y actualidad ===== */
  { id: "trend-busqueda-voz", tema: "La gente ya le pregunta a su móvil en voz alta: ¿te encuentra?", angulo: "preguntas naturales y respuestas claras en tu web", img: "golden sound waves of a voice query traveling from a silhouette to a glowing shop on a dark map, cinematic voice search visualization" },
  { id: "trend-ia-responde-google", tema: "Google ahora responde con IA: cómo seguir apareciendo", angulo: "contenido claro, estructurado y con autoridad local", img: "a glowing golden answer box of light hovering above traditional search results, dark interface, cinematic evolution of search" },
  { id: "trend-cliente-impaciente", tema: "El cliente de hoy no espera: la economía de la inmediatez", angulo: "respuesta en minutos o cliente perdido: la nueva vara de medir", img: "a golden fast-forward symbol made of light trails speeding through a dark city toward a responsive shop, cinematic urgency" },
  { id: "trend-hiperlocal", tema: "Hiperlocal: ganar tu barrio antes que tu país", angulo: "la proximidad como estrategia de contenido y de servicio", img: "a golden circle of light expanding from one shop across a dark neighborhood map, radius growing, cinematic local dominance" },
  { id: "trend-resenas-video", tema: "La reseña en vídeo: la nueva prueba social definitiva", angulo: "un cliente hablando 20 segundos vale más que diez párrafos", img: "a smartphone playing a glowing video testimonial of golden light, surrounding text reviews dimmer, dark space, cinematic social proof" },
  { id: "trend-mensajeria-ventas", tema: "El teléfono ya no suena: la venta llega por mensaje", angulo: "adaptar tu proceso comercial al canal que el cliente prefiere", img: "a vintage ringing telephone fading while a glowing golden chat bubble rises, dark transition scene, cinematic generational shift" },
  { id: "trend-transparencia", tema: "Precios visibles online: la transparencia que filtra curiosos y atrae compradores", angulo: "mostrar rangos ahorra tiempo a todos", img: "a clear golden price tag of light glowing on an elegant dark display, honesty atmosphere, cinematic clarity" },
  { id: "trend-sostenibilidad-local", tema: "Lo local y lo cercano como argumento de venta moderno", angulo: "kilómetro cero, trato humano y comunidad: valores que ya venden", img: "a golden heart of light connecting a local shop to surrounding homes on a dark map, community warmth, cinematic values" },

  /* ===== V. Email y seguimiento ===== */
  { id: "email-lista-propia", tema: "Tu lista de correos es el único público que es tuyo", angulo: "las redes te prestan audiencia; tu lista no te la puede quitar nadie", img: "a golden vault of light protecting glowing contact cards, dark treasury, ownership atmosphere, cinematic security" },
  { id: "email-bienvenida", tema: "El email de bienvenida que nadie envía y todos agradecen", angulo: "automático, cálido y con el siguiente paso claro", img: "a glowing golden envelope opening with warm light spilling out like a sunrise, dark elegant desk, cinematic welcome" },
  { id: "email-recuperar-inactivos", tema: "El correo que despierta clientes dormidos", angulo: "un 'te echamos de menos' con razón para volver", img: "a golden letter of light flying into a dark sleeping house and lighting a window, revival atmosphere, cinematic reconnection" },
  { id: "email-newsletter-pyme", tema: "La newsletter de una pyme: menos diseño, más cercanía", angulo: "una carta breve del dueño supera a la plantilla corporativa", img: "a personal handwritten letter glowing with golden sincerity beside a flashy corporate template in shadow, dark desk, cinematic authenticity" },
  { id: "email-asunto-que-abren", tema: "El asunto que hace que abran tu correo (sin trucos baratos)", angulo: "específico, personal y con beneficio claro", img: "a golden key of light unlocking a glowing envelope, dark mailbox atmosphere, cinematic open-rate metaphor" },
  { id: "email-automatico-secuencia", tema: "La secuencia automática que acompaña al cliente sin agobiar", angulo: "bienvenida, valor, prueba y oferta: cuatro correos bien dosificados", img: "four golden envelopes of light spaced evenly along an elegant dark timeline, rhythm and pacing, cinematic sequence" },
  { id: "email-carrito-formulario", tema: "El formulario abandonado: la segunda oportunidad que casi nadie aprovecha", angulo: "el mensaje amable que recupera al que se fue a medias", img: "a glowing half-filled form of golden light being gently completed by a helping hand of light, dark background, cinematic recovery" },
  { id: "email-medir-aperturas", tema: "Cuánta gente abre tus correos (y qué hacer con ese número)", angulo: "aperturas y clics explicados para decidir, no para presumir", img: "golden open envelopes of light rising like balloons from a dark analytics panel, measurement atmosphere, cinematic insight" }
];
